version: "3"
services:
  web:
    build: ./web-api
    ports:
      - 3001:3000
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=rariho
      - MYSQL_PASSWORD=rariho
      - MYSQL_DATABASE=rariho
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=rariho
      - MONGO_PASSWORD=rariho
      - MONGO_DATABASE=rariho
    volumes:
      - ./web-api:/app
    depends_on:
      - mysql
      - mongo
    networks:
      - rariho-network
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: rariho
      TZ: Asia/Tokyo
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo/db:/data/db
      - ./docker/mongo/configdb:/data/configdb
      - ./docker/mongo/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - rariho-network
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: rariho
      MYSQL_USER: rariho
      MYSQL_PASSWORD: rariho
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    networks:
      - rariho-network

networks:
  rariho-network:
    driver: bridge